version: '3.9'

networks:
  default:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: agenda-backend/Dockerfile
    container_name: agenda-backend
    ports:
      - "8080:8080" # Porta do backend
    environment:
      - DB_CONNECTION=mysql://${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

#  frontend:
#    build:
#      context: agenda-frontend
#      dockerfile: Dockerfile
#    container_name: agenda-frontend
#    ports:
#      - "3000:3000" # Porta do frontend React
#    stdin_open: true # Para interatividade, útil para desenvolvimento
#    tty: true        # Para interatividade, útil para desenvolvimento

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
